### PR TITLE
Add execute

### PR DESCRIPTION
**Pull request by LeventHAN**
Will allow socketIO to execute all possible RCON commands from remote

### CODE REVIEW

**Comment by Thomas-Smyth** [comment]
I don't get the point of this pull request, the child class will inherit the super class' `execute` method so why redefine it to what it's already defined as?

**Comment by LeventHAN** [comment]
Well if you remember I did try to execute it (rcon.execute) however it was not working cz the super class... Therefor I must do this, as you also confirmed it would work like this.

I will double check this to be 200% sure 👍

**Comment by 11TStudio** [comment]
Well if you remember I did try to execute it (rcon.execute) however it was not working cz the super class... Therefor I must do this, as you also confirmed it would work like this.

I will double check this to be 200% sure 👍

**Comment by LeventHAN** [comment]
Converting to draft until I'm able to test the stuff we spoke via PM

**Comment by Thomas-Smyth** [comment]
Going to close this for now.

**Pull request closed without merging**
