### PR TITLE
Add option to load admin lists via FTP

### PR DESCRIPTION
**Pull request by mbartisan**
The admin-list system now supports loading the Admins.cfg file via FTP, significantly improving compatibility with game server providers. By setting the admin-list configuration type to ftp and providing an FTP URL as the source, the Admins.cfg file will be downloaded into a buffer and parsed by the rest of the system.

```json
    {
        "type": "ftp",
        "source": "ftp://<user>:<password>@<host>:<port>/<url-path>"
      }
```

### CODE REVIEW

**Comment by werewolfboy13** [comment]
@mbartisan Are we able to provide some documentation in the template folders?

**Comment by mbartisan** [comment]
@werewolfboy13 Yeah I can. I also forgot to commit my removal of the debug logs. I'll update the PR in a sec.

**Comment by werewolfboy13** [comment]
Then please run `yarn build-all`. You will need to have ran `yarn install --ignore-engines` If it is not installed locally yet.

**Comment by mbartisan** [comment]
@werewolfboy13 Latest is pushed. Lmk if there are any other docs that should get updated.

**Comment by werewolfboy13** [comment]
There is, see above. May want to lint as well `yarn lint`

**Comment by mbartisan** [comment]
@werewolfboy13 Updated. The build and linter modified some files that were outside of my changes. They're in separate commits for each if any should get culled.

**Review by werewolfboy13 — APPROVED** [review]

**Comment by werewolfboy13** [comment]
@mbartisan that is fine. I always do squash and merge.

**Pull request merged**
