### PR TITLE
updated config and readme for adminlists

### PR DESCRIPTION
**Pull request by werewolfboy13**

### CODE REVIEW

**Comment by got2bhockey** [comment]
@werewolfboy13 You'll need to update this file as well to have the readme not get overwritten when it is regenerated:
https://github.com/Thomas-Smyth/SquadJS/blob/beta/squad-server/templates/readme-template.md

**Comment by Thomas-Smyth** [comment]
I think it would be a good idea to add the full examples removed in this commit: https://github.com/Thomas-Smyth/SquadJS/commit/23518b4d976a89ae96dc4d32098341560998789d

That way people can see examples of how to use `remote` and `local` as the options.

**Comment by werewolfboy13** [comment]
How do you think on this commits? Want it worded any way different?

**Comment by Thomas-Smyth** [comment]
I would havve just added it to the example above that, exactly how it was before it was removed.

**Comment by werewolfboy13** [comment]
This better?

**Comment by Thomas-Smyth** [comment]
Yeah, that will do, thanks.

**Comment by werewolfboy13** [comment]
Thanks I forgot to undo the indentation that VS likes to do.

**Pull request merged**
