### PR TITLE
Bumped Discord.js to v14.11.0 + discord plugins + log-parser

### PR DESCRIPTION
**Pull request by magicoflolis**
# Background

Been working with SquadJS for 3 months, it's great, but could be greater!

## Additions & Changes

`core/log-parser/index.js`

- Improved log parser
  - Inspired from uBlock Origin domWatcher. [link](https://github.com/gorhill/uBlock/blob/8e010f9c87cd92c5619a4c3f174150c4cd0c3cfc/src/js/contentscript.js#L320)
  - *Requires more testing*
- Fixed `Average matching latency` being NaN in the log.

`squad-server/package.json`

- Bumped discord.js to v14.11.0
- This will allow additional functionalities along with buttons and interactions.
  - *It is difficult to find well written documentation for v12.3.1*
  - For me it became easier to learn discord.js with a more recent version. [https://discordjs.guide/](https://discordjs.guide/)

`squad-server/factory.js`

- Reworked discord section for newer version

`squad-server/plugins/*`

- `cbl-info.js`, added exception for when there is no SteamID within the data ("possible log parser issue or data is not always available during trigger event").
- `discord-base-plugin.js`, reworked sendDiscordMessage function, added additional utility functions

`squad-server/plugins/discord-*.js`

- Rewrote how plugins use sendDiscordMessage function

While writing this I might have missed a few issues

- sendDiscordMessage function must be used with EmbedBuilder class.
- `cbl-info.js` may only display the default footer and not `Powered by SquadJS and the Community Ban List`
- Changes made have been tested & used for the past 3 months.
- Note, commit files are not the exact same files used for testing.

### CODE REVIEW

**Comment by werewolfboy13** [comment]
@magicoflolis Has this been tested on an live server?

**Comment by werewolfboy13** [comment]
Also more likely for versioning we may ask you to make separate PRs for each major change. That is something I’ll have to read into the bot with.

**Comment by lbzepoqo** [comment]
> Also more likely for versioning we may ask you to make separate PRs for each major change. That is something I’ll have to read into the bot with.

This is a good suggestion by werewolfboy. I would like to test it, but I am hesitant to test these all at once. A separate PR for each major change might make it easier to track and understand with better details.

**Comment by magicoflolis** [comment]
Merged changed to a new branch & created a new pull request https://github.com/Team-Silver-Sphere/SquadJS/pull/300

**Pull request closed without merging**
