### PR TITLE
Update Socket.io package

### LINKED ISSUE #263: [Socket.io] Depends on engine.io with known issues
### Description of Issue
SquadJS depends on an old version of socket.io which depends on an instance of engine.io with known problems
https://github.com/advisories/GHSA-r7qp-cfhv-p84w

remediation by upgrading the socket.io dependancy to a version that doesnt depend on engine.io with this fault resolves the problem. I've been running SquadJS with socket.io@4.5.4 and engine.io@6.2.1 for a few days without encountering any new faults.

### Errors or Screenshots of Issue
https://github.com/advisories/GHSA-r7qp-cfhv-p84w

### Squad Information
 * SquadJS Version: 3.6.1 release
 * Squad Version: N/A

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: RHEL9
 * NodeJS Version: v18.12.1
 * Yarn Version: v8.19.2

### PR DESCRIPTION
**Pull request by DrKittens**
resolves https://github.com/Team-Silver-Sphere/SquadJS/issues/263

### CODE REVIEW

**Comment by werewolfboy13** [comment]
Before this is approved I will need more testers to validate that this is a stable fix. @DrKittens

**Review by werewolfboy13 — CHANGES_REQUESTED** [review]
Needs more testing before PR can be pushed as this is a major version bump.

**Comment by DrKittens** [comment]
Please advise if there is a test sheet i can run through to assist with this & #265

**Comment by ect0s** [comment]
Impact here is only the socket.io plugin and whatever external sources use it. 

I think this is *probably* fine as is.

I believe Kitten may already be using Squad whitelister/Stats Pro which are the two projects that depend on socket.io.

**Review by werewolfboy13 — APPROVED** [review]

**Review by ect0s — APPROVED** [review]

**Pull request merged**
