### PR TITLE
Potential Fix to Warn Spam

### PR DESCRIPTION
**Pull request by werewolfboy13**
This fix should correct the issue if a player is in a squad and prevent them from getting warned. It appears to be working on our server.

### CODE REVIEW

**Review by LeventHAN — COMMENTED** [review]
Would it not be enough to just put this to head of the function `if(!this.trackedPlayers.includes(tracker.player.steamID)) return;`
Regarding the speed your solution would be better but that would not fix the issue I believe...

**Comment by Thomas-Smyth** [comment]
Odd this is being called... I'd have thought the timeout would have been removed when the player is untracked: https://github.com/Thomas-Smyth/SquadJS/blob/8b960ce7eb74bf10307dfd097b4b3717be27b53d/squad-server/plugins/auto-kick-unassigned.js#L245

**Comment by werewolfboy13** [comment]
It warns one time then stops warning if they are in a squad.

**Comment by LeventHAN** [comment]
> It warns one time then stops warning if they are in a squad.

So do I understand correctly?
1 - Players is without squad.
2 - Gets warned multiple times, until he joins a squad.
3 - Player joins a squad
4 - Gets still warned, **but** only one time...

**Comment by werewolfboy13** [comment]
Correct how it was explained to me is that after it warns one more time it will stop then. It does warn then drops the flag/tracker.

**Comment by LeventHAN** [comment]
> Correct how it was explained to me is that after it warns one more time it will stop then. It does warn then drops the flag/tracker.

Alright so after testing around. I found the solution.
**Issue**
When players join squad, the list of already tracking players is not getting updated. Which results in gettin another warning when player is still in squad. Until it updates (after 30 sec basiclly, but meanwhile the player is already in squad so gets only 1 time warning)

**To fix that**
You need to force update the tracking list when someone emits onPlayerSquadChange...

So basicly just do this:
```js
  async onPlayerSquadChange(player) {
    await this.updateTrackingList(true); // This forces to update the tracking list
    if (player.steamID in this.trackedPlayers && player.squadID !== null)
      this.untrackPlayer(player.steamID);
  }
```

**Comment by werewolfboy13** [comment]
I have a WIP for this when I have time I will update it/

**Pull request closed without merging**
