### PR TITLE
Improve tank detection in layer data

### PR DESCRIPTION
**Pull request by fantinodavide**

### CODE REVIEW

**Comment by werewolfboy13** [comment]
So I am the pipeline maintainer, what is the use case again for this?

**Comment by fantinodavide** [comment]
The regex `/tank/` is used to determine if a vehicle is a tank, but was also matching other vehicles whose icon is "map_jeep_antitank"

**Comment by werewolfboy13** [comment]
Have we checked that no tanks will be missed with this change? I can check the SDK output if needed.

image

**Review by ect0s — APPROVED** [review]
This Looks correct to me, 

I did pull down the layers.json and run a few grep expressions on it. Without this fix, we do collide on jeep_antitank. 

And with the fix it appears to be correct. 

The only edge case, would be if the "icon" type is mislabeled on a vehicle which would be upstream in the wiki code. 
```
cat _tank.txt | sort | uniq -c
    415             "icon": "map_tank",
cat tank.txt | sort | uniq -c
    194             "icon": "map_jeep_antitank",
    415             "icon": "map_tank",
```

**Review by werewolfboy13 — APPROVED** [review]

**Pull request merged**
